[colors-dark]
alpha=0.7
foreground=f8f4cd
#background=111111 #262423
regular0=1e1e1e # black
regular1=d2111b # red
regular2=ccd223 #868715 # green
regular3=e4981e # yellow
regular4=469295 # blue
regular5=c15889 # magenta
regular6=6eaf6e # cyan
regular7=dc4f0e # white
bright0=262423  # bright black
bright1=f73028  # bright red
bright2=aab01e  # bright green
bright3=f7b125  # bright yellow
bright4=719586  # bright blue
bright5=c77089  # bright magenta
bright6=7db669  # bright cyan
bright7=fb6a16  # bright white
